notifications:
  email:
    recipients:
      - millian.poquet@gmail.com
    on_success: change
    on_failure: always

sudo: required
dist: trusty

before_install:
  - export RSG_BASE_DIR=$(pwd)

  # Update apt lists
  - cat /etc/apt/sources.list
  - cp /etc/apt/sources.list /tmp/sources.list
  - echo 'deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse' >> /tmp/sources.list
  - echo 'deb-src http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse' >> /tmp/sources.list
  - sudo mv /tmp/sources.list /etc/apt/sources.list

install:
  # Install packages from apt
  - sudo apt-get -qq update
  - sudo apt install -y cmake # cmake
  - sudo apt install -y libboost-all-dev/xenial # boost
  - sudo apt install -y libzmq3-dev # zeromq
  - sudo apt install -y libunwind-dev libdw-dev libelf-dev libevent-dev # SG MC

  # Install SimGrid
  - cd ${RSG_BASE_DIR}
  - git clone https://github.com/simgrid/simgrid.git --branch master  --single-branch simgrid
  - cd simgrid
  - git checkout 55da8092d # 2018-02-28
  - mkdir build
  - cd build
  - cmake .. -Denable_compile_warnings=OFF -Denable_compile_optimizations=OFF -Denable_model-checking=ON -Denable_smpi=ON -Denable_documentation=OFF
  - make -j $(nproc)
  - sudo make install

  # Install thrift
  - cd ${RSG_BASE_DIR}
  - wget http://apache.lauf-forum.at/thrift/0.9.3/thrift-0.9.3.tar.gz
  - tar -xvf thrift-0.9.3.tar.gz
  - cd thrift-0.9.3
  - ./configure
  - make -j $(nproc)
  - sudo make install

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

# Build steps
script:
  ################
  # Build RSG #
  ################
  - cd ${RSG_BASE_DIR}
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -Denable_warnings=ON -Dtreat_warnings_as_errors=ON
  - make -j $(nproc)

  #########
  # Tests #
  #########
  - cd ${RSG_BASE_DIR}/build
  - ctest --output-on-failure -E 'turnon_turnoff|actor_kill_pid'
