notifications:
  email:
    recipients:
      - millian.poquet@gmail.com
      - martin.quinson@ens-rennes.fr
    on_success: change
    on_failure: always

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - libzmq3-dev
      - libboost-all-dev

before_install:
  - export RSG_BASE_DIR=$(pwd)

  # Update apt lists
  - cat /etc/apt/sources.list
  - cp /etc/apt/sources.list /tmp/sources.list
  - echo 'deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse' >> /tmp/sources.list
  - echo 'deb-src http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse' >> /tmp/sources.list
  - sudo mv /tmp/sources.list /etc/apt/sources.list

install:
  # Install SimGrid
  - cd ${RSG_BASE_DIR}
  - git clone https://github.com/simgrid/simgrid.git --depth=1 --branch master  --single-branch simgrid
  - cd simgrid
  - cmake . -Denable_compile_warnings=OFF -Denable_compile_optimizations=OFF -Denable_model-checking=OFF -Denable_smpi=OFF -Denable_documentation=OFF
  - make -j $(nproc)
  - sudo make install

  # Install thrift
  - cd ${RSG_BASE_DIR}
  - wget http://apache.lauf-forum.at/thrift/0.9.3/thrift-0.9.3.tar.gz
  - tar -xvf thrift-0.9.3.tar.gz
  - cd thrift-0.9.3
  - ./configure  --without-qt4 --without-qt5 --without-c_glib --without-csharp --without-java  --without-erlang --without-nodejs --without-lua --without-python --without-perl --without-php --without-php_extension --without-ruby --without-haskell --without-go --without-haxe --without-d
  - make -j $(nproc)
  - sudo make install

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

# Build steps
script:
  ################
  # Build RSG #
  ################
  - cd ${RSG_BASE_DIR}
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -Denable_warnings=ON -Dtreat_warnings_as_errors=OFF
  - make -j $(nproc) || VERBOSE=1 make

  #########
  # Tests #
  #########
  - cd ${RSG_BASE_DIR}/build
  - ctest --output-on-failure -E 'turnon_turnoff|actor_kill_pid'
