# This is the configuration file for the https://circleci.com/ continuous integration server
#
# Copyright (C) 2017. The SimGrid team. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the license (GNU LGPL) which comes with this package.

version: 2.0
jobs:
  build:
    docker:
      - image: simgrid/rsg_ci

compile:
  override:
    - mkdir -p ${CIRCLE_WORKING_DIRECTORY}/build
    - cd ${CIRCLE_WORKING_DIRECTORY}/build
    - nix-shell /datamovepkgs -A remote_simgrid \
                --command "cmake .. \
                                 -DCMAKE_BUILD_TYPE=Debug \
                                 -Denable_warnings=ON \
                                 -Dtreat_warnings_as_errors=OFF"
    - nix-shell /datamovepkgs -A remote_simgrid --command "make -j 4"

test:
  override:
    - nix-shell /datamovepkgs -A remote_simgrid \
          --command "export LC_ALL='en_US.UTF-8' && \
                     ctest --output-on-failure \
                           -E 'actor_kill_pid|turnon_turnoff'"
