# This is the configuration file for the https://circleci.com/ continuous integration server
#
# Copyright (C) 2017-2018. The SimGrid team. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the license (GNU LGPL) which comes with this package.

defaults: &defaults
  docker:
    - image: simgrid/rsg_ci

version: 2.0
jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create build directory
          command: mkdir build
      - run:
          name: Run CMake
          command: >
            cd build &&
            nix-shell /datamovepkgs -A remote_simgrid \
                      --command "cmake .. \
                                       -DCMAKE_BUILD_TYPE=Debug \
                                       -Denable_warnings=ON \
                                       -Dtreat_warnings_as_errors=OFF"
      - run:
          name: Do build with make
          command: >
            cd build &&
            nix-shell /datamovepkgs -A remote_simgrid \
                      --command "make -j $(nproc) || VERBOSE=1 make"
      - run:
          name: Run the tests with ctest
          command: >
            cd build &&
            nix-shell /datamovepkgs -A remote_simgrid \
                      --command "export LC_ALL='en_US.UTF-8' && \
                                ctest --output-on-failure"

#workflows:
#  version: 2
#  build_and_test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build
